# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.18.4

# Mod Properties
mod_version = 1.4.1-1.21.4-fabric
loader=fabric
maven_group = net.soulsweaponry
archives_base_name = soulslike-weaponry
modid=soulsweapons

# Dependencies
fabric_version=0.119.4+1.21.4
midninghtlib_version=2.2.0

geckolib_minecraft_version=1.21.4
geckolib_version=4.8.5

attributefix_version=21.4.2
attributefix_minecraft_version=1.21.4

#ranged_weapon_api_version = 2.1.1+1.21.1

# Compile time
rei_version = 18.0.808
prometheus_version = 1.1.2
prometheus_minecraft_version = 1.21

# Runtime
prickle=1023259:6914042
jade = 17.2.2+fabric
