package net.soulsweaponry.registry;

import net.minecraft.item.*;
import net.minecraft.util.Rarity;
import net.minecraftforge.registries.RegistryObject;
import net.soulsweaponry.items.*;
import net.soulsweaponry.items.material.ModToolMaterials;

import static net.soulsweaponry.SoulsWeaponry.MAIN_GROUP;

public class WeaponRegistry {

    public static RegistryObject<ToolItem> BLUEMOON_SHORTSWORD;
    public static RegistryObject<ToolItem> BLUEMOON_GREATSWORD;
    public static RegistryObject<ToolItem> MOONLIGHT_SHORTSWORD;
    public static RegistryObject<ToolItem> MOONLIGHT_GREATSWORD;
    public static RegistryObject<ToolItem> PURE_MOONLIGHT_GREATSWORD;
    public static RegistryObject<ToolItem> BLOODTHIRSTER;
    public static RegistryObject<DetonateGroundItem> DARKIN_BLADE;
    public static RegistryObject<ToolItem> DRAGON_STAFF;
    public static RegistryObject<ToolItem> WITHERED_WABBAJACK;
    public static RegistryObject<ToolItem> WHIRLIGIG_SAWBLADE;
    public static RegistryObject<ToolItem> DRAGONSLAYER_SWORDSPEAR;
    public static RegistryObject<ToolItem> GUINSOOS_RAGEBLADE;
    public static RegistryObject<ToolItem> GUTS_SWORD;
    public static RegistryObject<ToolItem> NIGHTFALL;
    public static RegistryObject<DetonateGroundItem> COMET_SPEAR;
    public static RegistryObject<ToolItem> LICH_BANE;
    public static RegistryObject<BowItem> GALEFORCE;
    public static RegistryObject<ToolItem> TRANSLUCENT_SWORD;
    public static RegistryObject<ToolItem> TRANSLUCENT_GLAIVE;
    public static RegistryObject<ToolItem> TRANSLUCENT_DOUBLE_GREATSWORD;
    public static RegistryObject<ToolItem> DRAUGR;
    public static RegistryObject<ToolItem> DAWNBREAKER;
    public static RegistryObject<ToolItem> SOUL_REAPER;
    public static RegistryObject<ToolItem> FORLORN_SCYTHE;
    public static RegistryObject<ToolItem> LEVIATHAN_AXE;
    public static RegistryObject<ToolItem> SKOFNUNG;
    public static RegistryObject<ToolItem> MJOLNIR;
    public static RegistryObject<ToolItem> FREYR_SWORD;
    public static RegistryObject<ToolItem> STING;
    public static RegistryObject<ToolItem> FEATHERLIGHT;
    public static RegistryObject<ToolItem> CRUCIBLE_SWORD;
    public static RegistryObject<ToolItem> DARKIN_SCYTHE_PRE;
    public static RegistryObject<ToolItem> DARKIN_SCYTHE_PRIME;
    public static RegistryObject<ToolItem> SHADOW_ASSASSIN_SCYTHE;
    public static RegistryObject<TrickWeapon> KIRKHAMMER;
    public static RegistryObject<TrickWeapon> SILVER_SWORD;
    public static RegistryObject<TrickWeapon> HOLY_GREATSWORD;
    public static RegistryObject<ToolItem> DRAUPNIR_SPEAR;
    public static RegistryObject<HolyMoonlightGreatsword> HOLY_MOONLIGHT_GREATSWORD;
    public static RegistryObject<TrickWeapon> HOLY_MOONLIGHT_SWORD;
    public static RegistryObject<Frostmourne> FROSTMOURNE;
    public static RegistryObject<ToolItem> MASTER_SWORD;
    public static RegistryObject<ToolItem> NIGHTS_EDGE_ITEM;
    public static RegistryObject<ToolItem> EMPOWERED_DAWNBREAKER;
    public static RegistryObject<BowItem> KRAKEN_SLAYER;
    public static RegistryObject<CrossbowItem> KRAKEN_SLAYER_CROSSBOW;
    public static RegistryObject<BowItem> DARKMOON_LONGBOW;

    public static void register() {
        BLUEMOON_SHORTSWORD = ItemRegistry.registerItem("bluemoon_shortsword", () -> new BluemoonShortsword(ModToolMaterials.MOONSTONE_OR_VERGLAS, -2.4F, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.RARE)));
        BLUEMOON_GREATSWORD = ItemRegistry.registerItem("bluemoon_greatsword", () -> new BluemoonGreatsword(ModToolMaterials.MOONSTONE_OR_VERGLAS, -2.8F, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.RARE)));
        MOONLIGHT_SHORTSWORD = ItemRegistry.registerItem("moonlight_shortsword", () -> new MoonlightShortsword(ModToolMaterials.MOONSTONE_OR_VERGLAS, -2.4F, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.EPIC)));
        MOONLIGHT_GREATSWORD = ItemRegistry.registerItem("moonlight_greatsword", () -> new MoonlightGreatsword(ModToolMaterials.MOONSTONE_OR_VERGLAS, -2.8F, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.EPIC)));
        PURE_MOONLIGHT_GREATSWORD = ItemRegistry.registerItem("pure_moonlight_greatsword", () -> new PureMoonlightGreatsword(ModToolMaterials.MOONSTONE_OR_VERGLAS, -2.8F, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.EPIC)));
        BLOODTHIRSTER = ItemRegistry.registerItem("bloodthirster", () -> new Bloodthirster(ModToolMaterials.CRIMSON_INGOT, -2.4F, new Item.Settings().group(MAIN_GROUP).fireproof().rarity(Rarity.EPIC)));
        DARKIN_BLADE = ItemRegistry.registerItem("darkin_blade", () -> new DarkinBlade(ModToolMaterials.CRIMSON_INGOT, -3F, new Item.Settings().group(MAIN_GROUP).fireproof().rarity(Rarity.EPIC)));
        DRAGON_STAFF = ItemRegistry.registerItem("dragon_staff", () -> new DragonStaff(ModToolMaterials.MOONSTONE_OR_VERGLAS, -2.8f, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.EPIC)));
        WITHERED_WABBAJACK = ItemRegistry.registerItem("withered_wabbajack", () -> new WitheredWabbajack(ModToolMaterials.MOONSTONE_OR_VERGLAS, -2.8f, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.EPIC).fireproof()));
        WHIRLIGIG_SAWBLADE = ItemRegistry.registerItem("whirligig_sawblade", () -> new WhirligigSawblade(ModToolMaterials.IRON_BLOCK, -2.4f, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.EPIC)));
        DRAGONSLAYER_SWORDSPEAR = ItemRegistry.registerItem("dragonslayer_swordspear", () -> new DragonslayerSwordspear(ModToolMaterials.MOONSTONE_OR_VERGLAS, -2.6f, new Item.Settings().group(MAIN_GROUP).fireproof().rarity(Rarity.EPIC)));
        GUINSOOS_RAGEBLADE = ItemRegistry.registerItem("rageblade", () -> new GuinsoosRageblade(ModToolMaterials.MOONSTONE_OR_VERGLAS, -2.4f, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.EPIC)));
        GUTS_SWORD = ItemRegistry.registerItem("guts_sword", () -> new DragonslayerSwordBerserk(ModToolMaterials.IRON_BLOCK, -3f, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.EPIC)));
        NIGHTFALL = ItemRegistry.registerItem("nightfall", () -> new Nightfall(ModToolMaterials.IRON_BLOCK, -3, new Item.Settings().group(MAIN_GROUP).fireproof().rarity(Rarity.EPIC)));
        COMET_SPEAR = ItemRegistry.registerItem("comet_spear", () -> new CometSpear(ModToolMaterials.MOONSTONE_OR_VERGLAS, -2.6f, new Item.Settings().group(MAIN_GROUP).fireproof().rarity(Rarity.EPIC)));
        LICH_BANE = ItemRegistry.registerItem("lich_bane", () -> new LichBane(ModToolMaterials.MOONSTONE_OR_VERGLAS, -2.4f, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.EPIC)));
        GALEFORCE = ItemRegistry.registerItem("galeforce", () -> new Galeforce(new Item.Settings().group(MAIN_GROUP).fireproof().maxDamage(1300).rarity(Rarity.EPIC)));
        TRANSLUCENT_SWORD = ItemRegistry.registerItem("translucent_sword", () -> new SwordItem(ModToolMaterials.LOST_SOUL, 6, -2.4F, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.RARE)));
        TRANSLUCENT_GLAIVE = ItemRegistry.registerItem("translucent_glaive", () -> new SwordItem(ModToolMaterials.LOST_SOUL, 7, -2.6F, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.RARE)));
        TRANSLUCENT_DOUBLE_GREATSWORD = ItemRegistry.registerItem("translucent_double_greatsword", () -> new SwordItem(ModToolMaterials.LOST_SOUL, 8, -2.8F, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.RARE)));
        DRAUGR = ItemRegistry.registerItem("draugr", () -> new Draugr(ModToolMaterials.MOONSTONE_OR_VERGLAS, -2.4f, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.EPIC)));
        DAWNBREAKER = ItemRegistry.registerItem("dawnbreaker", () -> new Dawnbreaker(ModToolMaterials.MOONSTONE_OR_VERGLAS, -2.4f, new Item.Settings().group(MAIN_GROUP).fireproof().rarity(Rarity.EPIC)));
        SOUL_REAPER = ItemRegistry.registerItem("soul_reaper", () -> new SoulReaper(ModToolMaterials.MOONSTONE_OR_VERGLAS, -3f, new Item.Settings().group(MAIN_GROUP).fireproof().rarity(Rarity.EPIC)));
        FORLORN_SCYTHE = ItemRegistry.registerItem("forlorn_scythe", () -> new ForlornScythe(ModToolMaterials.LOST_SOUL, -3f, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.UNCOMMON)));
        LEVIATHAN_AXE = ItemRegistry.registerItem("leviathan_axe", () -> new LeviathanAxe(ModToolMaterials.MOONSTONE_OR_VERGLAS, -2.8f, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.EPIC).fireproof()));
        SKOFNUNG = ItemRegistry.registerItem("skofnung", () -> new Skofnung(ModToolMaterials.MOONSTONE_OR_VERGLAS, -2.4f, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.EPIC).fireproof()));
        MJOLNIR = ItemRegistry.registerItem("mjolnir", () -> new Mjolnir(ModToolMaterials.MOONSTONE_OR_VERGLAS, -2.8f, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.EPIC).fireproof()));
        FREYR_SWORD = ItemRegistry.registerItem("freyr_sword", () -> new FreyrSword(ModToolMaterials.MOONSTONE_OR_VERGLAS, -2.4f, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.EPIC).fireproof()));
        STING = ItemRegistry.registerItem("sting", () -> new Sting(ModToolMaterials.MOONSTONE_OR_VERGLAS, -2.4f, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.RARE)));
        FEATHERLIGHT = ItemRegistry.registerItem("featherlight", () -> new Featherlight(ModToolMaterials.MOONSTONE_OR_VERGLAS, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.RARE)));
        CRUCIBLE_SWORD = ItemRegistry.registerItem("crucible_sword", () -> new CrucibleSword(ModToolMaterials.MOONSTONE_OR_VERGLAS, -2.4f, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.EPIC).fireproof()));
        DARKIN_SCYTHE_PRE = ItemRegistry.registerItem("darkin_scythe_pre", () -> new DarkinScythePre(ModToolMaterials.MOONSTONE_OR_VERGLAS, -3f, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.EPIC).fireproof()));
        DARKIN_SCYTHE_PRIME = ItemRegistry.registerItem("darkin_scythe", () -> new DarkinScythePrime(ModToolMaterials.MOONSTONE_OR_VERGLAS, -3f, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.EPIC).fireproof()));
        SHADOW_ASSASSIN_SCYTHE = ItemRegistry.registerItem("shadow_assassin_scythe", () -> new ShadowAssassinScythe(ModToolMaterials.MOONSTONE_OR_VERGLAS, -3f, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.EPIC).fireproof()));
        KIRKHAMMER = ItemRegistry.registerItem("kirkhammer", () -> new TrickWeapon(ModToolMaterials.IRON_BLOCK, 0, -3f, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.RARE), 1, 0, true, false));
        SILVER_SWORD = ItemRegistry.registerItem("silver_sword", () -> new TrickWeapon(ModToolMaterials.IRON_BLOCK, 1, -2.4f, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.RARE), 0, 1, false, true));
        HOLY_GREATSWORD = ItemRegistry.registerItem("holy_greatsword", () -> new TrickWeapon(ModToolMaterials.IRON_BLOCK, 2, -2.8f, new Item.Settings().group(MAIN_GROUP).rarity(Rarity.RARE), 1, 2, false, true));
        DRAUPNIR_SPEAR = ItemRegistry.registerItem("draupnir_spear", () -> new DraupnirSpear(ModToolMaterials.MOONSTONE_OR_VERGLAS, -2.6f,  new Item.Settings().group(MAIN_GROUP).fireproof().rarity(Rarity.EPIC)));
        HOLY_MOONLIGHT_GREATSWORD = ItemRegistry.registerItem("holy_moonlight_greatsword", () -> new HolyMoonlightGreatsword(ModToolMaterials.MOONSTONE_OR_VERGLAS, -2.8f,  new Item.Settings().group(MAIN_GROUP).fireproof().rarity(Rarity.EPIC), 4));
        HOLY_MOONLIGHT_SWORD = ItemRegistry.registerItem("holy_moonlight_sword", () -> new HolyMoonlightSword(ModToolMaterials.MOONSTONE_OR_VERGLAS, -2.4f,  new Item.Settings().group(MAIN_GROUP).fireproof().rarity(Rarity.EPIC)));
        FROSTMOURNE = ItemRegistry.registerItem("frostmourne", () -> new Frostmourne(ModToolMaterials.MOONSTONE_OR_VERGLAS, -2.4f,  new Item.Settings().group(MAIN_GROUP).fireproof().rarity(Rarity.EPIC)));
        MASTER_SWORD = ItemRegistry.registerItem("master_sword", () -> new MasterSword(ModToolMaterials.MOONSTONE_OR_VERGLAS, -2.4f, new Item.Settings().group(MAIN_GROUP).fireproof().rarity(Rarity.EPIC)));
        NIGHTS_EDGE_ITEM = ItemRegistry.registerItem("nights_edge_item", () -> new NightsEdgeItem(ModToolMaterials.MOONSTONE_OR_VERGLAS, -2.8f, new Item.Settings().group(MAIN_GROUP).fireproof().rarity(Rarity.EPIC)));
        EMPOWERED_DAWNBREAKER = ItemRegistry.registerItem("empowered_dawnbreaker", () -> new EmpoweredDawnbreaker(ModToolMaterials.MOONSTONE_OR_VERGLAS, -2.8f, new Item.Settings().group(MAIN_GROUP).fireproof().rarity(Rarity.EPIC)));
        KRAKEN_SLAYER = ItemRegistry.registerItem("kraken_slayer", () -> new KrakenSlayer(new Item.Settings().group(MAIN_GROUP).maxDamage(1258).fireproof().rarity(Rarity.EPIC)));
        KRAKEN_SLAYER_CROSSBOW = ItemRegistry.registerItem("kraken_slayer_crossbow", () -> new KrakenSlayerCrossbow(new Item.Settings().group(MAIN_GROUP).fireproof().maxDamage(1258).rarity(Rarity.EPIC)));
        DARKMOON_LONGBOW = ItemRegistry.registerItem("darkmoon_longbow", () -> new DarkmoonLongbow(new Item.Settings().group(MAIN_GROUP).fireproof().maxDamage(1400).rarity(Rarity.EPIC)));
    }
}
