package net.soulsweaponry.config;

public class ConfigConstructor extends MidnightConfig {

    @Entry public static float item_upgrading_max_level = 5f;

    @Entry public static boolean inform_player_about_disabled_use = true;
    @Entry public static boolean inform_player_about_no_bound_freyr_sword = true;
    @Entry public static boolean inform_player_about_no_soulbound_thrown_weapon = true;
    @Entry public static boolean inform_player_about_cooldown_effect = true;
    @Entry public static boolean inform_player_about_no_souls_to_collect = true;
    @Entry public static boolean inform_player_about_collected_souls = true;
    @Entry public static boolean inform_player_about_out_of_range = true;
    @Entry public static boolean inform_player_about_disabled_boss_respawning = true;

    @Entry public static boolean disable_weapon_recipes = false;
    @Entry public static boolean disable_gun_recipes = false;
    @Entry public static boolean disable_armor_recipes = false;

    @Entry public static boolean disable_all_enchantments = false;
    @Entry public static boolean disable_enchantment_fast_hands = false;
    @Entry public static boolean disable_enchantment_posture_breaker = false;
    @Entry public static boolean disable_enchantment_stagger = false;
    @Entry public static boolean disable_enchantment_ethereal_ammunition = false;
    @Entry public static boolean disable_enchantment_explosive_rounds = false;
    @Entry public static boolean disable_enchantment_chain_lightning = false;
    @Entry public static boolean disable_enchantment_misfire_curse = false;
    @Entry public static boolean disable_enchantment_blight_carrier = false;
    @Entry public static boolean disable_enchantment_frostsilver = false;
    @Entry public static boolean disable_enchantment_phantom_trace = false;
    @Entry public static boolean disable_enchantment_tether = false;
    @Entry public static boolean disable_enchantment_ricochet = false;

    @Entry public static boolean disable_recipe_bloodthirster = false;
    @Entry public static boolean disable_recipe_bluemoon_greatsword = false;
    @Entry public static boolean disable_recipe_bluemoon_shortsword = false;
    @Entry public static boolean disable_recipe_comet_spear = false;
    @Entry public static boolean disable_recipe_darkin_blade = false;
    @Entry public static boolean disable_recipe_dawnbreaker = false;
    @Entry public static boolean disable_recipe_heap_of_raw_iron = false;
    @Entry public static boolean disable_recipe_dragonslayer_swordspear = false;
    @Entry public static boolean disable_recipe_dragon_staff = false;
    @Entry public static boolean disable_recipe_draugr = false;
    @Entry public static boolean disable_recipe_galeforce = false;
    @Entry public static boolean disable_recipe_rageblade = false;
    @Entry public static boolean disable_recipe_lich_bane = false;
    @Entry public static boolean disable_recipe_moonlight_greatsword = false;
    @Entry public static boolean disable_recipe_moonlight_shortsword = false;
    @Entry public static boolean disable_recipe_nightfall = false;
    @Entry public static boolean disable_recipe_soul_reaper = false;
    @Entry public static boolean disable_recipe_forlorn_scythe = true;
    @Entry public static boolean disable_recipe_whirligig_sawblade = false;
    @Entry public static boolean disable_recipe_withered_wabbajack = false;
    @Entry public static boolean disable_recipe_leviathan_axe = false;
    @Entry public static boolean disable_recipe_skofnung = false;
    @Entry public static boolean disable_recipe_pure_moonlight_greatsword = false;
    @Entry public static boolean disable_recipe_mjolnir = false;
    @Entry public static boolean disable_recipe_sword_of_freyr = false;
    @Entry public static boolean disable_recipe_sting = false;
    @Entry public static boolean disable_recipe_featherlight = false;
    @Entry public static boolean disable_recipe_crucible_sword = false;
    @Entry public static boolean disable_recipe_darkin_scythe = false;
    @Entry public static boolean disable_recipe_kirkhammer = false;
    @Entry public static boolean disable_recipe_ludwigs_holy_blade = false;
    @Entry public static boolean disable_recipe_draupnir_spear = false;
    @Entry public static boolean disable_recipe_holy_moonlight_sword = false;
    @Entry public static boolean disable_recipe_master_sword = false;
    @Entry public static boolean disable_recipe_frostmourne = false;
    @Entry public static boolean disable_recipe_nights_edge = false;
    @Entry public static boolean disable_recipe_empowered_dawnbreaker = false;
    @Entry public static boolean disable_recipe_kraken_slayer_bow = true;
    @Entry public static boolean disable_recipe_kraken_slayer_crossbow = false;
    @Entry public static boolean disable_recipe_darkmoon_longbow = false;
    @Entry public static boolean disable_recipe_translucent_sword = false;
    @Entry public static boolean disable_recipe_translucent_glaive = false;
    @Entry public static boolean disable_recipe_translucent_double_edged_greatsword = false;
    @Entry public static boolean disable_recipe_chungus_staff = true;
    @Entry public static boolean disable_recipe_dark_moon_greatsword = false;
    @Entry public static boolean disable_recipe_glaive_of_hodir = false;
    @Entry public static boolean disable_recipe_excalibur = false;
    @Entry public static boolean disable_recipe_moonveil = false;
    @Entry public static boolean disable_recipe_simons_bowblade = false;
    @Entry public static boolean disable_recipe_dragonbane = false;
    @Entry public static boolean disable_recipe_supernova = false;
    @Entry public static boolean disable_recipe_mehrunes_razor = false;
    @Entry public static boolean disable_recipe_tonitrus = false;
    @Entry public static boolean disable_recipe_bloodlust = false;
    @Entry public static boolean disable_recipe_sword_of_the_nightlord = false;

    @Entry public static boolean disable_recipe_arkenplate = false;
    @Entry public static boolean disable_recipe_chaos_helmet = false;
    @Entry public static boolean disable_recipe_soul_ingot_helmet = false;
    @Entry public static boolean disable_recipe_soul_ingot_chestplate = false;
    @Entry public static boolean disable_recipe_soul_ingot_leggings = false;
    @Entry public static boolean disable_recipe_soul_ingot_boots = false;
    @Entry public static boolean disable_recipe_soul_robes_helmet = false;
    @Entry public static boolean disable_recipe_soul_robes_chestplate = false;
    @Entry public static boolean disable_recipe_soul_robes_leggings = false;
    @Entry public static boolean disable_recipe_soul_robes_boots = false;
    @Entry public static boolean disable_recipe_forlorn_helmet = false;
    @Entry public static boolean disable_recipe_forlorn_chestplate = false;
    @Entry public static boolean disable_recipe_forlorn_leggings = false;
    @Entry public static boolean disable_recipe_forlorn_boots = false;
    @Entry public static boolean disable_recipe_withered_chest = false;

    @Entry public static boolean disable_recipe_enhanced_arkenplate = false;
    @Entry public static boolean disable_recipe_enhanced_withered_chest = false;

    @Entry public static boolean disable_use_bluemoon_shortsword = false;
    @Entry public static boolean disable_use_bluemoon_greatsword = false;
    @Entry public static boolean disable_use_moonlight_shortsword = false;
    @Entry public static boolean disable_use_moonlight_greatsword = false;
    @Entry public static boolean disable_use_pure_moonlight_greatsword = false;
    @Entry public static boolean disable_use_bloodthirster = false;
    @Entry public static boolean disable_use_darkin_blade = false;
    @Entry public static boolean disable_use_dragon_staff = false;
    @Entry public static boolean disable_use_withered_wabbajack = false;
    @Entry public static boolean disable_use_whirligig_sawblade = false;
    @Entry public static boolean disable_use_dragonslayer_swordspear = false;
    @Entry public static boolean disable_use_rageblade = false;
    @Entry public static boolean disable_use_heap_of_raw_iron = false;
    @Entry public static boolean disable_use_nightfall = false;
    @Entry public static boolean disable_use_comet_spear = false;
    @Entry public static boolean disable_use_lich_bane = false;
    @Entry public static boolean disable_use_galeforce = false;
    @Entry public static boolean disable_use_draugr = false;
    @Entry public static boolean disable_use_dawnbreaker = false;
    @Entry public static boolean disable_use_soul_reaper = false;
    @Entry public static boolean disable_use_forlorn_scythe = false;
    @Entry public static boolean disable_use_leviathan_axe = false;
    @Entry public static boolean disable_use_skofnung = false;
    @Entry public static boolean disable_use_skofnung_stone = false;
    @Entry public static boolean disable_use_mjolnir = false;
    @Entry public static boolean disable_use_sword_of_freyr = false;
    // @Entry public static boolean disable_use_sting = false;
    @Entry public static boolean disable_use_featherlight = false;
    @Entry public static boolean disable_use_crucible_sword = false;
    @Entry public static boolean disable_use_darkin_scythe = false;
    @Entry public static boolean disable_use_darkin_scythe_prime = false;
    @Entry public static boolean disable_use_shadow_assassin_scythe = false;
    @Entry public static boolean disable_use_draupnir_spear = false;
    @Entry public static boolean disable_use_holy_moonlight_greatsword = false;
    @Entry public static boolean disable_use_holy_moonlight_sword = false;
    @Entry public static boolean disable_use_frostmourne = false;
    @Entry public static boolean disable_use_master_sword = false;
    @Entry public static boolean disable_use_nights_edge = false;
    @Entry public static boolean disable_use_empowered_dawnbreaker = false;
    @Entry public static boolean disable_use_kraken_slayer_bow = false;
    @Entry public static boolean disable_use_kraken_slayer_crossbow = false;
    @Entry public static boolean disable_use_darkmoon_longbow = false;
    @Entry public static boolean disable_use_hunter_pistol = false;
    @Entry public static boolean disable_use_hunter_blunderbuss = false;
    @Entry public static boolean disable_use_gatling_gun = false;
    @Entry public static boolean disable_use_hunter_cannon = false;
    @Entry public static boolean disable_use_kirkhammer = false;
    @Entry public static boolean disable_use_silver_sword = false;
    @Entry public static boolean disable_use_ludwigs_holy_greatsword = false;
    @Entry public static boolean disable_use_moonstone_ring = false;
    @Entry public static boolean disable_use_chaos_orb = false;
    @Entry public static boolean disable_use_translucent_weapons = false;
    @Entry public static boolean disable_use_chungus_staff = false;
    @Entry public static boolean disable_use_dark_moon_greatsword = false;
    @Entry public static boolean disable_use_glaive_of_hodir = false;
    @Entry public static boolean disable_use_excalibur = false;
    @Entry public static boolean disable_use_moonveil = false;
    @Entry public static boolean disable_use_simons_bowblade = false;
    @Entry public static boolean disable_use_simons_blade = false;
    @Entry public static boolean disable_use_dragonbane = false;
    @Entry public static boolean disable_use_supernova = false;
    @Entry public static boolean disable_use_mehrunes_razor = false;
    @Entry public static boolean disable_use_tonitrus = false;
    @Entry public static boolean disable_use_bloodlust = false;
    @Entry public static boolean disable_use_sword_of_the_nightlord = false;

    @Entry public static boolean disable_use_arkenplate = false;
    @Entry public static boolean disable_use_chaos_crown = false;
    @Entry public static boolean disable_use_chaos_robes = false;
    @Entry public static boolean disable_use_hallowheart = false;
    @Entry public static boolean disable_use_soul_ingot_armor = false;
    @Entry public static boolean disable_use_soul_robes_armor = false;
    @Entry public static boolean disable_use_forlorn_armor = false;

    @Entry public static boolean is_fireproof_bloodthirster = true;
    @Entry public static boolean is_fireproof_bluemoon_greatsword = false;
    @Entry public static boolean is_fireproof_bluemoon_shortsword = false;
    @Entry public static boolean is_fireproof_comet_spear = true;
    @Entry public static boolean is_fireproof_darkin_blade = true;
    @Entry public static boolean is_fireproof_dawnbreaker = true;
    @Entry public static boolean is_fireproof_heap_of_raw_iron = false;
    @Entry public static boolean is_fireproof_dragonslayer_swordspear = true;
    @Entry public static boolean is_fireproof_dragon_staff = true;
    @Entry public static boolean is_fireproof_draugr = true;
    @Entry public static boolean is_fireproof_galeforce = true;
    @Entry public static boolean is_fireproof_rageblade = true;
    @Entry public static boolean is_fireproof_lich_bane = true;
    @Entry public static boolean is_fireproof_moonlight_greatsword = true;
    @Entry public static boolean is_fireproof_moonlight_shortsword = true;
    @Entry public static boolean is_fireproof_moonlight_ring = true;
    @Entry public static boolean is_fireproof_nightfall = true;
    @Entry public static boolean is_fireproof_soul_reaper = true;
    @Entry public static boolean is_fireproof_forlorn_scythe = true;
    @Entry public static boolean is_fireproof_whirligig_sawblade = true;
    @Entry public static boolean is_fireproof_withered_wabbajack = true;
    @Entry public static boolean is_fireproof_leviathan_axe = true;
    @Entry public static boolean is_fireproof_skofnung = true;
    @Entry public static boolean is_fireproof_pure_moonlight_greatsword = true;
    @Entry public static boolean is_fireproof_mjolnir = true;
    @Entry public static boolean is_fireproof_sword_of_freyr = true;
    @Entry public static boolean is_fireproof_sting = false;
    @Entry public static boolean is_fireproof_featherlight = true;
    @Entry public static boolean is_fireproof_crucible_sword = true;
    @Entry public static boolean is_fireproof_darkin_scythe = true;
    @Entry public static boolean is_fireproof_darkin_scythe_prime = true;
    @Entry public static boolean is_fireproof_shadow_assassin_scythe = true;
    @Entry public static boolean is_fireproof_kirkhammer = false;
    @Entry public static boolean is_fireproof_ludwigs_holy_blade = false;
    @Entry public static boolean is_fireproof_silver_sword = false;
    @Entry public static boolean is_fireproof_draupnir_spear = true;
    @Entry public static boolean is_fireproof_holy_moonlight_sword = true;
    @Entry public static boolean is_fireproof_holy_moonlight_greatsword = true;
    @Entry public static boolean is_fireproof_master_sword = true;
    @Entry public static boolean is_fireproof_frostmourne = true;
    @Entry public static boolean is_fireproof_nights_edge = true;
    @Entry public static boolean is_fireproof_empowered_dawnbreaker = true;
    @Entry public static boolean is_fireproof_kraken_slayer_bow = true;
    @Entry public static boolean is_fireproof_kraken_slayer_crossbow = true;
    @Entry public static boolean is_fireproof_darkmoon_longbow = true;
    @Entry public static boolean is_fireproof_translucent_weapons = false;
    @Entry public static boolean is_fireproof_chungus_staff = false;
    @Entry public static boolean is_fireproof_dark_moon_greatsword = true;
    @Entry public static boolean is_fireproof_glaive_of_hodir = true;
    @Entry public static boolean is_fireproof_excalibur = true;
    @Entry public static boolean is_fireproof_moonveil = true;
    @Entry public static boolean is_fireproof_simons_bowblade = false;
    @Entry public static boolean is_fireproof_simons_blade = false;
    @Entry public static boolean is_fireproof_dragonbane = true;
    @Entry public static boolean is_fireproof_supernova = true;
    @Entry public static boolean is_fireproof_mehrunes_razor = true;
    @Entry public static boolean is_fireproof_tonitrus = false;
    @Entry public static boolean is_fireproof_bloodlust = false;
    @Entry public static boolean is_fireproof_sword_of_the_nightlord = true;

    @Entry public static boolean is_fireproof_blunderbuss = false;
    @Entry public static boolean is_fireproof_gatling_gun = false;
    @Entry public static boolean is_fireproof_hunter_cannon = false;
    @Entry public static boolean is_fireproof_hunter_pistol = false;

    @Entry public static boolean is_fireproof_arkenplate = true;
    @Entry public static boolean is_fireproof_chaos_crown = true;
    @Entry public static boolean is_fireproof_chaos_helmet = true;
    @Entry public static boolean is_fireproof_chaos_robes = false;
    @Entry public static boolean is_fireproof_hallowheart = true;

    @Entry public static boolean is_fireproof_soul_ingot_set = false;
    @Entry public static boolean is_fireproof_soul_robes_set = false;
    @Entry public static boolean is_fireproof_forlorn_set = true;

    @Entry(min=0) public static float withered_demon_spawnweight = 20;
    @Entry(min=0) public static float moderatly_sized_chungus_spawnweight = 100;
    @Entry public static float chungus_monolith_radius = 32;
    @Entry(min=0) public static float evil_forlorn_spawnweight = 15;

    @Entry public static boolean can_withered_demon_spawn = true;
    @Entry public static boolean can_moderatly_sized_chungus_spawn = true;
    @Entry public static boolean can_evil_forlorn_spawn = true;

    @Entry public static boolean can_bosses_break_blocks = true;

    @Entry public static float[] chaos_armor_armor_points = {4, 7, 10, 5};
    @Entry public static float[] chaos_armor_base_posture_increase = {0, 0, 0, 0};
    @Entry public static float[] chaos_armor_posture_buildup_resistances = {0, 0, 0, 0};
    @Entry public static float[] chaos_armor_bleed_buildup_resistances = {40, 70, 100, 60};
    @Entry public static float[] chaos_armor_bleed_damage_resistances = {30, 50, 60, 40};

    @Entry public static float[] chaos_set_armor_points = {2, 3, 4, 1};
    @Entry public static float[] chaos_set_base_posture_increase = {0, 0, 0, 0};
    @Entry public static float[] chaos_set_posture_buildup_resistances = {0, 0, 0, 0};
    @Entry public static float[] chaos_set_bleed_buildup_resistances = {0, 0, 0, 0};
    @Entry public static float[] chaos_set_bleed_damage_resistances = {0, 0, 0, 0};

    @Entry public static float[] soul_ingot_armor_points = {3, 5, 7, 3};
    @Entry public static float[] soul_ingot_base_posture_increase = {0, 0, 0, 0};
    @Entry public static float[] soul_ingot_posture_buildup_resistances = {0, 0, 0, 0};
    @Entry public static float[] soul_ingot_bleed_buildup_resistances = {2.5f, 7.5f, 10, 5};
    @Entry public static float[] soul_ingot_bleed_damage_resistances = {2, 4, 6, 3};

    @Entry public static float[] soul_robes_armor_points = {2, 3, 4, 3};
    @Entry public static float[] soul_robes_base_posture_increase = {0, 0, 0, 0};
    @Entry public static float[] soul_robes_posture_buildup_resistances = {0, 0, 0, 0};
    @Entry public static float[] soul_robes_bleed_buildup_resistances = {0, 0, 0, 0};
    @Entry public static float[] soul_robes_bleed_damage_resistances = {0, 0, 0, 0};

    @Entry public static float[] forlorn_armor_armor_points = {3, 6, 8, 3};
    @Entry public static float[] forlorn_armor_base_posture_increase = {10, 20, 35, 15};
    @Entry public static float[] forlorn_armor_posture_buildup_resistances = {20, 40, 50, 30};
    @Entry public static float[] forlorn_armor_bleed_buildup_resistances = {35, 50, 75, 40};
    @Entry public static float[] forlorn_armor_bleed_damage_resistances = {10, 30, 40, 20};

    @Entry public static float[] withered_armor_armor_points = {4, 7, 10, 5};
    @Entry public static float[] withered_armor_base_posture_increase = {0, 0, 0, 0};
    @Entry public static float[] withered_armor_posture_buildup_resistances = {10, 20, 25, 15};
    @Entry public static float[] withered_armor_bleed_buildup_resistances = {15, 30, 40, 25};
    @Entry public static float[] withered_armor_bleed_damage_resistances = {0, 0, 0, 0};

    @Entry public static boolean chaos_cape_wither_ground = true;
    @Entry public static float chaos_crown_luck_given = 1;
    @Entry public static float chaos_crown_flip_effect_cooldown = 300;
    @Entry public static float chaos_crown_flip_effect_min_cooldown = 100;
    @Entry public static boolean chaos_crown_flip_effect_enchant_reduces_cooldown = false;
    @Entry public static String[] chaos_crown_flip_effect_enchant_reduces_cooldown_ids = {"unbreaking"};
    @Entry public static float arkenplate_shockwave_cooldown = 200;
    @Entry public static float arkenplate_shockwave_min_cooldown = 80;
    @Entry public static boolean arkenplate_shockwave_enchant_reduces_cooldown = false;
    @Entry public static String[] arkenplate_shockwave_enchant_reduces_cooldown_ids = {"unbreaking"};
    @Entry public static float arkenplate_shockwave_knockback = 2f;
    @Entry public static float arkenplate_shockwave_damage = 6f;
    @Entry(min=0,max=1) public static float arkenplate_mirror_trigger_percent = 0.5f;
    @Entry public static float forlorn_set_bonus_range = 6f;
    @Entry public static float forlorn_set_bonus_heal = 2f;
    @Entry(min=0,max=1) public static float withered_chest_strength_trigger_percent_1 = 0.5f;
    @Entry(min=0,max=1) public static float withered_chest_strength_trigger_percent_2 = 0.25f;
    @Entry public static float withered_chest_ability_cooldown = 500;
    @Entry public static float withered_chest_ability_min_cooldown = 100;
    @Entry public static boolean withered_chest_ability_enchant_reduces_cooldown = false;
    @Entry public static String[] withered_chest_ability_enchant_reduces_cooldown_ids = {"unbreaking"};
    @Entry public static float withered_chest_apply_wither_duration = 100;
    @Entry public static float withered_chest_apply_wither_amplifier = 0;
    @Entry public static float withered_chest_apply_fire_seconds = 6;
    @Entry public static float withered_chest_life_leach_duration = 400;
    @Entry public static float withered_chest_life_leach_amplifier = 0;

    @Entry public static float bloodlust_damage = 7;
    @Entry public static float bloodlust_attack_speed = 1.6f;
    @Entry public static float bloodlust_bleed_post_hit = 40;
    @Entry public static float bloodlust_bleed_post_hit_bonus_per_bloodthirsty_amp = 30;
    @Entry public static float bloodlust_ability_self_damage = 4f;
    @Entry public static float bloodlust_ability_self_bleed = 100;
    @Entry public static float bloodlust_ability_strength_amp = 1;
    @Entry public static float bloodlust_ability_strength_duration = 400;
    @Entry public static float bloodlust_ability_bloodthirsty_amp = 0;
    @Entry public static float bloodlust_ability_bloodthirsty_duration = 300;
    @Entry public static float bloodlust_bloodloss_in_vicinity_gives_strength_amp = 0;
    @Entry public static float bloodlust_bloodloss_in_vicinity_gives_strength_duration = 600;
    @Entry public static float bloodthirster_damage = 8;
    @Entry public static float bloodthirster_attack_speed = 1.6f;
    @Entry public static float bloodthirster_life_steal_base_heal = 2f;
    @Entry public static float bloodthirster_life_steal_bonus_heal_per_level = 0.5f;
    @Entry public static float bloodthirster_life_steal_cooldown = 60;
    @Entry public static float bloodthirster_life_steal_min_cooldown = 10;
    @Entry public static float bloodthirster_life_steal_reduced_cooldown_per_level = 10;
    @Entry public static float bloodthirster_overheal_base_absorption_amp = 0;
    @Entry public static float bloodthirster_overheal_bonus_absorption_amp_per_level = 0.5f;
    @Entry public static float bloodthirster_overheal_base_absorption_duration = 100;
    @Entry public static float bloodthirster_overheal_bonus_absorption_duration_per_level = 10;
    @Entry public static float bloodthirster_overheal_cooldown = 60;
    @Entry public static float bloodthirster_overheal_min_cooldown = 10;
    @Entry public static float bloodthirster_overheal_reduced_cooldown_per_level = 10;
    @Entry public static float bluemoon_greatsword_damage = 8;
    @Entry public static float bluemoon_greatsword_attack_speed = 1.2f;
    @Entry public static float bluemoon_greatsword_charge_needed = 8;
    @Entry public static float bluemoon_greatsword_charge_added_post_hit = 1;
    @Entry public static float bluemoon_greatsword_projectile_damage = 8.0f;
    @Entry public static float bluemoon_greatsword_projectile_velocity = 1.5f;
    @Entry public static float bluemoon_shortsword_damage = 7;
    @Entry public static float bluemoon_shortsword_attack_speed = 1.6f;
    @Entry public static float bluemoon_shortsword_projectile_damage = 3.0f;
    @Entry public static float bluemoon_shortsword_projectile_velocity = 1.5f;
    @Entry public static float bluemoon_shortsword_projectile_cooldown = 120;
    @Entry public static float bluemoon_shortsword_projectile_min_cooldown = 10;
    @Entry public static boolean bluemoon_shortsword_enchant_reduces_cooldown = false;
    @Entry public static String[] bluemoon_shortsword_enchant_reduces_cooldown_ids = {"damage"};
    @Entry public static float chungus_staff_damage = 9;
    @Entry public static float chungus_staff_attack_speed = 1.1f;
    @Entry public static float chungus_staff_ticks_before_explosion = 15;
    @Entry public static float chungus_staff_use_cooldown = 5;
    @Entry public static float chungus_staff_ability_cooldown = 2400;
    @Entry public static boolean chungus_staff_enchant_reduces_cooldown = true;
    @Entry public static String[] chungus_staff_enchant_reduces_cooldown_ids = {"damage"};
    @Entry public static float comet_spear_damage = 8;
    @Entry public static float comet_spear_attack_speed = 1.4f;
    @Entry public static float comet_spear_projectile_damage = 8.0f;
    @Entry public static float comet_spear_skyfall_ability_damage = 10;
    @Entry public static float comet_spear_skyfall_ability_cooldown = 400;
    @Entry public static float comet_spear_skyfall_ability_min_cooldown = 200;
    @Entry public static float comet_spear_skyfall_ability_reduced_cooldown_per_level = 20;
    @Entry public static float comet_spear_throw_ability_cooldown = 25;
    @Entry public static float comet_spear_throw_ability_min_cooldown = 0;
    @Entry public static float comet_spear_throw_ability_reduced_cooldown_per_level = 5;
    @Entry public static float comet_spear_calculated_fall_base_radius = 0f;
    @Entry public static float comet_spear_calculated_fall_height_increase_radius_modifier = 2f;
    @Entry public static float comet_spear_calculated_fall_max_radius = 100f;
    @Entry public static float comet_spear_calculated_fall_max_damage = 100f;
    @Entry public static float comet_spear_calculated_fall_height_increase_damage_modifier = 0.2f;
    @Entry public static float comet_spear_calculated_fall_target_launch_modifier = 0.0125f;
    @Entry public static float comet_spear_calculated_fall_target_max_launch_power = 1.1f;
    @Entry public static float comet_spear_calculated_fall_heal_from_damage_modifier = 0f;
    @Entry public static float crucible_sword_normal_damage = 9;
    @Entry public static float crucible_sword_attack_speed = 1.6f;
    @Entry public static float crucible_sword_empowered_damage = 30;
    @Entry public static float crucible_sword_empowered_cooldown = 300;
    @Entry public static float crucible_sword_empowered_min_cooldown = 100;
    @Entry public static float crucible_sword_empowered_cooldown_modifier_in_nether = 0.4f;
    @Entry public static boolean crucible_sword_enchant_reduces_cooldown = true;
    @Entry public static String[] crucible_sword_enchant_reduces_cooldown_ids = {"damage"};
    @Entry public static float darkin_blade_damage = 11;
    @Entry public static float darkin_blade_attack_speed = 1f;
    @Entry public static float darkin_blade_posture_loss = 30;
    @Entry public static float darkin_blade_omnivamp_base_heal = 4f;
    @Entry public static float darkin_blade_omnivamp_bonus_heal_per_level = 0.5f;
    @Entry public static float darkin_blade_omnivamp_cooldown = 50;
    @Entry public static float darkin_blade_omnivamp_min_cooldown = 10;
    @Entry public static float darkin_blade_omnivamp_reduced_cooldown_per_level = 8;
    @Entry public static float darkin_blade_ability_damage = 12;
    @Entry public static float darkin_blade_ability_cooldown = 150;
    @Entry public static float darkin_blade_ability_min_cooldown = 40;
    @Entry public static float darkin_blade_calculated_fall_base_radius = 3f;
    @Entry public static float darkin_blade_calculated_fall_height_increase_radius_modifier = 1.75f;
    @Entry public static float darkin_blade_calculated_fall_target_launch_modifier = 0.04f;
    @Entry public static float darkin_blade_calculated_fall_target_max_launch_power = 1.25f;
    @Entry public static float darkin_blade_calculated_fall_max_radius = 100f;
    @Entry public static float darkin_blade_calculated_fall_max_damage = 100f;
    @Entry public static float darkin_blade_calculated_fall_height_increase_damage_modifier = 0.2f;
    @Entry public static float darkin_blade_calculated_fall_heal_from_damage_modifier = 0.1f;
    @Entry public static float darkin_scythe_damage = 9;
    @Entry public static float darkin_scythe_attack_speed = 1f;
    @Entry public static float darkin_scythe_bonus_damage = 3;
    @Entry public static float darkin_scythe_max_souls = 100;
    @Entry public static float darkin_scythe_prime_umbral_trespass_damage = 20f;
    @Entry public static float darkin_scythe_prime_umbral_trespass_bonus_damage_per_level = 6f;
    @Entry public static float darkin_scythe_prime_umbral_trespass_bonus_enchant_damage_modifier = 1f;
    @Entry public static float darkin_scythe_prime_attack_speed = 1f;
    @Entry(min=0,max=1) public static double darkin_scythe_prime_umbral_trespass_bonus_percent_max_health_damage = 0.1f;
    @Entry public static float darkin_scythe_prime_umbral_trespass_cooldown = 400;
    @Entry public static float darkin_scythe_prime_umbral_trespass_min_cooldown = 100;
    @Entry public static float darkin_scythe_prime_umbral_trespass_reduced_cooldown_per_level = 25;
    @Entry public static float darkin_scythe_prime_umbral_trespass_heal_modifier = 0.25f;
    @Entry public static float darkin_scythe_prime_umbral_trespass_ticks_before_dismount = 80;
    @Entry public static float darkin_scythe_prime_omnivamp_base_heal = 4f;
    @Entry public static float darkin_scythe_prime_omnivamp_bonus_heal_per_level = 0.5f;
    @Entry public static float darkin_scythe_prime_omnivamp_cooldown = 50;
    @Entry public static float darkin_scythe_prime_omnivamp_min_cooldown = 10;
    @Entry public static float darkin_scythe_prime_omnivamp_reduced_cooldown_per_level = 8;
    @Entry public static float darkmoon_longbow_damage = 9;
    @Entry public static float darkmoon_longbow_bonus_velocity = 0f;
    @Entry public static float darkmoon_longbow_pull_time_ticks = 25;
    @Entry public static double darkmoon_longbow_ability_damage = 13D;
    @Entry public static float darkmoon_longbow_ability_cooldown_ticks = 150;
    @Entry public static float darkmoon_longbow_ability_min_cooldown_ticks = 60;
    @Entry public static boolean darkmoon_longbow_enchant_reduces_cooldown = true;
    @Entry public static String[] darkmoon_longbow_enchant_reduces_cooldown_ids = {"unbreaking"};
    @Entry public static boolean darkmoon_longbow_can_apply_arrow_effects = true;
    @Entry public static float dark_moon_greatsword_damage = 10;
    @Entry public static float dark_moon_greatsword_attack_speed = 1.2f;
    @Entry public static float dark_moon_greatsword_post_hit_permafrost_base_amplifier = 0;
    @Entry public static float dark_moon_greatsword_post_hit_permafrost_amp_per_level = 1f;
    @Entry public static float dark_moon_greatsword_post_hit_permafrost_base_duration = 100;
    @Entry public static float dark_moon_greatsword_frost_buildup_post_hit = 60;
    @Entry public static float dark_moon_greatsword_frost_moon_base_duration = 400;
    @Entry public static float dark_moon_greatsword_frost_moon_base_amplifier = 0;
    @Entry public static float dark_moon_greatsword_frost_moon_cooldown = 700;
    @Entry public static float dark_moon_greatsword_frost_moon_min_cooldown = 300;
    @Entry public static float dark_moon_greatsword_projectile_damage = 7f;
    @Entry public static float dark_moon_greatsword_projectile_permafrost_base_amplifier = 0;
    @Entry public static float dark_moon_greatsword_projectile_permafrost_base_duration = 200;
    @Entry public static float dawnbreaker_damage = 8;
    @Entry public static float dawnbreaker_attack_speed = 1.6f;
    @Entry public static float dawnbreaker_ability_damage = 10.0f;
    @Entry(min=0,max=1) public static double dawnbreaker_ability_percent_chance_addition = 0.0D;
    @Entry public static boolean dawnbreaker_affect_all_entities = false;
    @Entry public static float empowered_dawnbreaker_damage = 10;
    @Entry public static float empowered_dawnbreaker_attack_speed = 1.2f;
    @Entry public static float empowered_dawnbreaker_ability_damage = 15f;
    @Entry public static float empowered_dawnbreaker_ability_cooldown = 180;
    @Entry public static float empowered_dawnbreaker_ability_min_cooldown = 100;
    @Entry public static boolean empowered_dawnbreaker_ability_enchant_reduces_cooldown = false;
    @Entry public static String[] empowered_dawnbreaker_ability_enchant_reduces_cooldown_ids = {"fire_aspect"};
    @Entry public static float heap_of_raw_iron_damage = 10;
    @Entry public static float heap_of_raw_iron_attack_speed = 1f;
    @Entry public static float heap_of_raw_iron_posture_loss = 30;
    @Entry public static float heap_of_raw_iron_dragons_scourge_bonus = 3f;
    @Entry public static float heap_of_raw_iron_cooldown = 200;
    @Entry public static float heap_of_raw_iron_min_cooldown = 40;
    @Entry public static boolean heap_of_raw_iron_enchant_reduces_cooldown = false;
    @Entry public static String[] heap_of_raw_iron_enchant_reduces_cooldown_ids = {"unbreaking"};
    @Entry public static float heap_of_raw_iron_calculated_fall_base_radius = 2.5f;
    @Entry public static float heap_of_raw_iron_calculated_fall_height_increase_radius_modifier = 1.6f;
    @Entry public static float heap_of_raw_iron_calculated_fall_target_launch_modifier = 0.03f;
    @Entry public static float heap_of_raw_iron_calculated_fall_target_max_launch_power = 1.1f;
    @Entry public static float heap_of_raw_iron_calculated_fall_max_radius = 100f;
    @Entry public static float heap_of_raw_iron_calculated_fall_max_damage = 100f;
    @Entry public static float heap_of_raw_iron_calculated_fall_height_increase_damage_modifier = 0.2f;
    @Entry public static float heap_of_raw_iron_calculated_fall_heal_from_damage_modifier = 0f;
    @Entry public static float dragonbane_damage = 9;
    @Entry public static float dragonbane_attack_speed = 1.6f;
    @Entry public static float dragonbane_dragons_scourge_base_bonus = 20f;
    @Entry public static float dragonbane_dragons_scourge_bonus_per_level = 5f;
    @Entry public static float dragonbane_chain_lightning_base_damage = 6f;
    @Entry public static float dragonbane_chain_lightning_bonus_damage_per_level = 4f;
    @Entry public static float dragonbane_chain_lightning_base_range = 2.5f;
    @Entry public static float dragonbane_chain_lightning_bonus_range_per_level = 1.3f;
    @Entry public static float dragonslayer_swordspear_damage = 8;
    @Entry public static float dragonslayer_swordspear_attack_speed = 1.4f;
    @Entry public static float dragonslayer_swordspear_dragons_scourge_bonus = 2f;
    @Entry public static float dragonslayer_swordspear_dragons_scourge_bonus_per_level = 1f;
    @Entry public static float dragonslayer_swordspear_rain_bonus_damage = 1;
    @Entry public static float dragonslayer_swordspear_rain_bonus_attack_speed = 0.4f;
    @Entry public static float dragonslayer_swordspear_projectile_damage = 7.0f;
    @Entry public static float dragonslayer_swordspear_throw_cooldown = 100;
    @Entry public static float dragonslayer_swordspear_throw_min_cooldown = 20;
    @Entry public static float dragonslayer_swordspear_throw_reduced_cooldown_per_level = 15;
    @Entry public static float dragonslayer_swordspear_throw_cooldown_modifier_when_raining = 0.5f;
    @Entry public static float dragonslayer_swordspear_lightning_call_block_radius = 10;
    @Entry public static float dragonslayer_swordspear_lightning_call_lightning_amount = 1;
    @Entry public static float dragonslayer_swordspear_lightning_call_bonus_lightning_amount_per_level = 0.4f;
    @Entry public static float dragonslayer_swordspear_storm_stomp_damage = 6.0f;
    @Entry public static float dragonslayer_swordspear_storm_stomp_bonus_damage_per_level = 2f;
    @Entry public static float dragonslayer_swordspear_storm_stomp_knockback = 5f;
    @Entry public static float dragonslayer_swordspear_lightning_call_ability_cooldown = 300;
    @Entry public static float dragonslayer_swordspear_lightning_call_min_cooldown = 80;
    @Entry public static float dragonslayer_swordspear_lightning_call_reduced_cooldown_per_level = 35;
    @Entry public static float dragonslayer_swordspear_lightning_call_cooldown_modifier_when_raining = 0.5f;
    @Entry public static float dragon_staff_damage = 8;
    @Entry public static float dragon_staff_attack_speed = 1.2f;
    @Entry public static float dragon_staff_aura_strength = 1;
    @Entry public static float dragon_staff_vigorous_fog_damage_and_heal = 2;
    @Entry public static boolean dragon_staff_vigorous_fog_heal_tamed_entities_owned_by_others = true;
    @Entry public static float dragon_staff_cooldown = 100;
    @Entry public static float dragon_staff_min_cooldown = 10;
    @Entry public static boolean dragon_staff_enchant_reduces_cooldown = true;
    @Entry public static String[] dragon_staff_enchant_reduces_cooldown_ids = {"damage"};
    @Entry public static float dragon_staff_use_time = 100;
    @Entry public static float draugr_damage_at_night = 11;
    @Entry public static float draugr_attack_speed = 1.6f;
    @Entry public static float draupnir_spear_damage = 8;
    @Entry public static float draupnir_spear_attack_speed = 1.4f;
    @Entry public static float draupnir_spear_projectile_damage = 10f;
    @Entry public static float draupnir_spear_detonate_power = 1f;
    @Entry public static float draupnir_spear_throw_cooldown = 40;
    @Entry public static float draupnir_spear_throw_min_cooldown = 10;
    @Entry public static float draupnir_spear_detonate_cooldown = 100;
    @Entry public static float draupnir_spear_detonate_min_cooldown = 40;
    @Entry public static float draupnir_spear_summon_spears_cooldown = 300;
    @Entry public static float draupnir_spear_summon_spears_min_cooldown = 80;
    @Entry public static boolean draupnir_spear_enchant_reduces_throw_cooldown = true;
    @Entry public static String[] draupnir_spear_enchant_reduces_throw_cooldown_ids = {"damage"};
    @Entry public static boolean draupnir_spear_enchant_reduces_ability_cooldown = false;
    @Entry public static String[] draupnir_spear_enchant_reduces_ability_cooldown_ids = {"damage"};
    @Entry public static float draupnir_spear_max_age = 400;
    @Entry public static float excalibur_damage = 8;
    @Entry public static float excalibur_attack_speed = 1.6f;
    @Entry(min=0, max=1D) public static double excalibur_life_guard_percent = 0.3;
    @Entry(min=0, max=1D) public static double excalibur_life_save_chance_percent = 0.3;
    @Entry public static float excalibur_life_save_explosion_damage = 10f;
    @Entry public static float excalibur_life_save_explosion_knockback = 1f;
    @Entry public static float excalibur_life_save_stack_damage = 20;
    @Entry public static float excalibur_sonic_boom_damage = 10f;
    @Entry public static float excalibur_sonic_boom_knockback_power = 0.5f;
    @Entry public static float excalibur_sonic_boom_cooldown = 100;
    @Entry public static float excalibur_sonic_boom_min_cooldown = 40;
    @Entry public static float excalibur_sonic_boom_max_range = 40f;
    @Entry public static float excalibur_sonic_boom_target_search_range = 16f;
    @Entry public static float excalibur_lightbringer_effects_duration = 300f;
    @Entry public static float excalibur_lightbringer_effects_amplifier = 0f;
    @Entry public static boolean excalibur_enchant_reduces_ability_cooldown = true;
    @Entry public static String[] excalibur_enchant_reduces_ability_cooldown_ids = {"damage"};
    @Entry public static float forlorn_scythe_damage = 11;
    @Entry public static float forlorn_scythe_attack_speed = 1f;
    @Entry public static float forlorn_scythe_wither_skull_explosion_power = 1f;
    @Entry public static float forlorn_scythe_empowered_wither_skull_explosion_power = 2f;
    @Entry public static float featherlight_damage = 8;
    @Entry public static float featherlight_attack_speed = 1.6f;
    @Entry public static float featherlight_posture_loss = 20;
    @Entry public static float featherlight_calculated_fall_base_radius = 2.5f;
    @Entry public static float featherlight_calculated_fall_height_increase_radius_modifier = 1.6f;
    @Entry public static float featherlight_calculated_fall_target_launch_modifier = 0.025f;
    @Entry public static float featherlight_calculated_fall_target_max_launch_power = 1.05f;
    @Entry public static float featherlight_calculated_fall_max_radius = 100f;
    @Entry public static float featherlight_calculated_fall_max_damage = 100f;
    @Entry public static float featherlight_calculated_fall_height_increase_damage_modifier = 0.2f;
    @Entry public static float featherlight_calculated_fall_heal_from_damage_modifier = 0f;
    @Entry public static float frostmourne_damage = 11;
    @Entry public static float frostmourne_attack_speed = 1.6f;
    @Entry public static float frostmourne_summoned_allies_cap = 50;
    @Entry public static float frostmourne_frost_buildup_post_hit = 40;
    @Entry public static float frostmourne_frost_post_hit_permafrost_base_duration = 160;
    @Entry public static float frostmourne_frost_post_hit_permafrost_base_amplifier = 0;
    @Entry public static float frostmourne_frost_post_hit_permafrost_amp_per_level = 1f;
    @Entry public static float galeforce_damage = 10;
    @Entry public static float galeforce_bonus_velocity = 0.25f;
    @Entry public static float galeforce_ability_velocity = 3f;
    @Entry public static float galeforce_pull_time_ticks = 20;
    @Entry public static float galeforce_speed_effect_duration_ticks = 50;
    @Entry public static float galeforce_speed_effect_amplifier = 4;
    @Entry public static float galeforce_dash_cooldown = 80;
    @Entry public static float galeforce_dash_min_cooldown = 20;
    @Entry public static boolean galeforce_dash_enchant_reduces_cooldown = false;
    @Entry public static String[] galeforce_dash_enchant_reduces_cooldown_ids = {"unbreaking"};
    @Entry public static boolean galeforce_can_apply_arrow_effects = true;
    @Entry public static float glaive_of_hodir_damage = 8;
    @Entry public static float glaive_of_hodir_attack_speed = 1.3f;
    @Entry public static float glaive_of_hodir_bonus_damage_per_stack = 0.8f;
    @Entry public static float glaive_of_hodir_bonus_attack_speed_per_stack = 0.1f;
    @Entry public static float glaive_of_hodir_max_stacks = 5;
    @Entry public static float glaive_of_hodir_add_effects_cooldown = 200;
    @Entry public static float glaive_of_hodir_effects_duration = 220;
    @Entry public static float glaive_of_hodir_resistance_amplifier = 2;
    @Entry public static float glaive_of_hodir_absorption_amplifier = 3;
    @Entry public static boolean glaive_of_hodir_enchant_reduces_cooldown = true;
    @Entry public static String[] glaive_of_hodir_enchant_reduces_cooldown_ids = {"damage"};
    @Entry public static float glaive_of_hodir_projectile_damage = 7f;
    @Entry public static float glaive_of_hodir_projectile_cooldown = 160;
    @Entry public static float glaive_of_hodir_projectile_min_cooldown = 80;
    @Entry public static float glaive_of_hodir_projectile_posture_loss = 125;
    @Entry public static float rageblade_damage = 7;
    @Entry public static float rageblade_attack_speed = 1.6f;
    @Entry public static boolean rageblade_haste_cap = true;
    @Entry public static float holy_moonlight_greatsword_damage = 10;
    @Entry public static float holy_moonlight_greatsword_attack_speed = 1.2f;
    @Entry public static float holy_moonlight_greatsword_righteous_base_undead_bonus_damage = 2f;
    @Entry public static float holy_moonlight_greatsword_righteous_undead_bonus_damage_per_level = 0.5f;
    @Entry public static float holy_moonlight_ability_charge_needed = 50;
    @Entry public static float holy_moonlight_greatsword_charge_added_post_hit = 3;
    @Entry public static float holy_moonlight_ability_damage = 20f;
    @Entry public static float holy_moonlight_ability_knockup = 0.3f;
    @Entry public static float holy_moonlight_ability_cooldown = 150;
    @Entry public static float holy_moonlight_ability_min_cooldown = 60;
    @Entry public static float holy_moonlight_ruptures_amount = 8;
    @Entry public static float holy_moonlight_sword_damage = 7;
    @Entry public static float holy_moonlight_sword_attack_speed = 1.6f;
    @Entry public static float holy_moonlight_sword_righteous_base_undead_bonus_damage = 2f;
    @Entry public static float holy_moonlight_sword_righteous_undead_bonus_damage_per_level = 0.5f;
    @Entry public static float holy_moonlight_sword_max_bonus_damage = 2;
    @Entry public static float holy_moonlight_sword_charge_added_post_hit = 1;
    @Entry public static float kirkhammer_damage = 9;
    @Entry public static float kirkhammer_attack_speed = 1f;
    @Entry public static float kirkhammer_posture_loss = 40;
    @Entry public static float kirkhammer_calculated_fall_base_radius = 2.5f;
    @Entry public static float kirkhammer_calculated_fall_height_increase_radius_modifier = 1.4f;
    @Entry public static float kirkhammer_calculated_fall_target_launch_modifier = 0.035f;
    @Entry public static float kirkhammer_calculated_fall_target_max_launch_power = 1f;
    @Entry public static float kirkhammer_calculated_fall_max_radius = 100f;
    @Entry public static float kirkhammer_calculated_fall_max_damage = 100f;
    @Entry public static float kirkhammer_calculated_fall_height_increase_damage_modifier = 0.15f;
    @Entry public static float kirkhammer_calculated_fall_heal_from_damage_modifier = 0f;
    @Entry public static float kirkhammer_calculated_fall_base_posture_loss = 25f;
    @Entry public static float kirkhammer_calculated_fall_height_increase_posture_loss_modifier = 3.5f;
    @Entry public static float kirkhammer_silver_sword_damage = 6;
    @Entry public static float kirkhammer_silver_sword_attack_speed = 1.6f;
    @Entry public static float kirkhammer_silver_sword_righteous_base_undead_bonus_damage = 2f;
    @Entry public static float kirkhammer_silver_sword_righteous_undead_bonus_damage_per_level = 0.5f;
    @Entry public static float kraken_slayer_damage = 7;
    @Entry public static String kraken_slayer_bow_use_animation = "SPEAR";
    @Entry public static float kraken_slayer_bonus_velocity = 0f;
    @Entry public static float kraken_slayer_pull_time_ticks = 10;
    @Entry public static float kraken_slayer_crossbow_damage = 9;
    @Entry public static float kraken_slayer_crossbow_bonus_velocity = 0f;
    @Entry public static float kraken_slayer_crossbow_pull_time_ticks = 15;
    @Entry public static float kraken_slayer_bonus_true_damage = 4f;
    @Entry public static float kraken_slayer_player_true_damage_taken_modifier = 0.4f;
    @Entry public static boolean kraken_slayer_can_apply_arrow_effects = true;
    @Entry public static float leviathan_axe_damage = 10;
    @Entry public static float leviathan_axe_attack_speed = 1.2f;
    @Entry public static float leviathan_axe_frost_buildup_post_hit = 50;
    @Entry public static float leviathan_axe_post_hit_permafrost_duration = 180;
    @Entry public static float leviathan_axe_post_hit_permafrost_base_amp = 0f;
    @Entry public static float leviathan_axe_post_hit_permafrost_amp_per_level = 1f;
    @Entry public static float leviathan_axe_projectile_base_speed = 2.5f;
    @Entry public static float leviathan_axe_projectile_speed_bonus_per_level = 0.2f;
    @Entry public static float leviathan_axe_projectile_frost_buildup_on_collision = 50;
    @Entry public static float leviathan_axe_projectile_damage = 7f;
    @Entry public static double leviathan_axe_return_speed = 4D;
    @Entry public static float lich_bane_damage = 7;
    @Entry public static float lich_bane_attack_speed = 1.6f;
    @Entry public static float lich_bane_bonus_magic_damage = 2f;
    @Entry public static float ludwigs_holy_greatsword_damage = 8;
    @Entry public static float ludwigs_holy_greatsword_attack_speed = 1.2f;
    @Entry public static float ludwigs_holy_greatsword_righteous_base_undead_bonus_damage = 2f;
    @Entry public static float ludwigs_holy_greatsword_righteous_undead_bonus_damage_per_level = 0.5f;
    @Entry public static float master_sword_damage = 8;
    @Entry public static float master_sword_attack_speed = 1.6f;
    @Entry public static float master_sword_righteous_base_undead_bonus_damage = 2f;
    @Entry public static float master_sword_righteous_undead_bonus_damage_per_level = 0.5f;
    @Entry public static float master_sword_projectile_damage = 11.0f;
    @Entry public static float mehrunes_razor_damage = 6f;
    @Entry public static float mehrunes_razor_attack_speed = 2f;
    @Entry(min=0) public static double mehrunes_razor_posture_break_crit_hit_percent_bonus = 1.0;
    @Entry public static float mehrunes_razor_missing_health_modifier = 0.75f;
    @Entry public static float mehrunes_razor_missing_health_modifier_against_players = 0.5f;
    @Entry public static float mehrunes_razor_missing_health_max_bonus_damage = 30f;
    @Entry public static float mehrunes_razor_missing_health_trigger_cap = 50f;
    @Entry public static float mehrunes_razor_kill_trigger_cap = 50f;
    @Entry(min=0, max=1) public static float mehrunes_razor_missing_health_chance_under_health_cap = 0.50f;
    @Entry(min=0, max=1) public static float mehrunes_razor_missing_health_chance_over_health_cap = 0.15f;
    @Entry(min=0, max=1) public static float mehrunes_razor_kill_chance_under_health_cap = 0.0198f;
    @Entry(min=0, max=1) public static float mehrunes_razor_kill_chance_over_health_cap = 0.005f;
    @Entry public static String[] mehrunes_razor_no_instakill_entity_blacklist = {
            "minecraft:chicken",
    };
    @Entry public static float mjolnir_damage = 9;
    @Entry public static float mjolnir_attack_speed = 1.2f;
    @Entry public static float mjolnir_rain_bonus_damage = 2;
    @Entry public static float mjolnir_rain_bonus_attack_speed = 0f;
    @Entry public static float mjolnir_projectile_damage = 7f;
    @Entry public static float mjolnir_lightning_base_smash_damage = 8f;
    @Entry public static float mjolnir_lightning_bonus_smash_damage_per_level = 1f;
    @Entry public static float mjolnir_lightning_enchant_bonus_smash_damage_multiplier = 2f;
    @Entry public static float mjolnir_lightning_circle_amount = 3;
    @Entry public static float mjolnir_lightning_smash_cooldown = 200;
    @Entry public static float mjolnir_lightning_smash_min_cooldown = 60;
    @Entry public static float mjolnir_lightning_smash_reduced_cooldown_per_level = 30;
    @Entry public static float mjolnir_riptide_cooldown = 300;
    @Entry public static float mjolnir_riptide_min_cooldown = 60;
    @Entry public static float mjolnir_riptide_reduced_cooldown_per_level = 30;
    @Entry public static double mjolnir_return_speed = 4D;
    @Entry public static float moonlight_greatsword_damage = 9;
    @Entry public static float moonlight_greatsword_attack_speed = 1.2f;
    @Entry public static float moonlight_greatsword_projectile_damage = 8.0f;
    @Entry public static float moonlight_greatsword_projectile_velocity = 1.5f;
    @Entry public static float pure_moonlight_greatsword_damage = 11;
    @Entry public static float pure_moonlight_greatsword_attack_speed = 1.2f;
    @Entry public static float pure_moonlight_greatsword_projectile_damage = 9.0f;
    @Entry public static float moonlight_shortsword_damage = 8;
    @Entry public static float moonlight_shortsword_attack_speed = 1.6f;
    @Entry public static float moonlight_shortsword_projectile_damage = 3.0f;
    @Entry public static float moonlight_shortsword_projectile_velocity = 1.5f;
    @Entry public static float moonlight_shortsword_projectile_cooldown = 13;
    @Entry public static float moonstone_ring_projectile_cooldown = 5;
    @Entry public static float moonstone_ring_lunar_herald_base_amplifier = 0;
    @Entry public static float moonstone_ring_lunar_herald_duration = 600;
    @Entry public static float moonveil_damage = 9;
    @Entry public static float moonveil_attack_speed = 1.6f;
    @Entry public static float moonveil_wave_base_damage = 8f;
    @Entry public static float moonveil_wave_bonus_damage_per_level = 2.5f;
    @Entry public static float moonveil_wave_cooldown = 30;
    @Entry public static float moonveil_wave_min_cooldown = 0;
    @Entry public static float moonveil_wave_reduced_cooldown_per_level = 10;
    @Entry public static float moonveil_vertical_base_damage = 12f;
    @Entry public static float moonveil_vertical_bonus_damage_per_level = 3f;
    @Entry public static float moonveil_vertical_cooldown = 30;
    @Entry public static float moonveil_vertical_min_cooldown = 0;
    @Entry public static float moonveil_vertical_reduced_cooldown_per_level = 10;
    @Entry public static float moonveil_bleed_post_hit = 25;
    @Entry public static float moonveil_bleed_post_hit_bonus_per_bloodthirsty_amp = 20;
    @Entry public static float nightfall_damage = 11;
    @Entry public static float nightfall_attack_speed = 1f;
    @Entry public static float nightfall_posture_loss = 40;
    @Entry public static float nightfall_shield_duration = 200;
    @Entry public static float nightfall_shield_absorption_amp = 2;
    @Entry public static float nightfall_shield_resistance_amp = 0;
    @Entry public static float nightfall_shield_cooldown = 500;
    @Entry public static float nightfall_shield_min_cooldown = 60;
    @Entry public static float nightfall_shield_reduced_cooldown_per_level = 70;
    @Entry public static float nightfall_obliterate_base_damage = 18.0f;
    @Entry public static float nightfall_obliterate_bonus_damage_per_level = 2.0f;
    @Entry public static float nightfall_obliterate_enchant_bonus_damage_modifier = 2.0f;
    @Entry public static float nightfall_obliterate_y_velocity_launch_power = 0.5f;
    @Entry public static float nightfall_obliterate_cooldown = 300;
    @Entry public static float nightfall_obliterate_min_cooldown = 80;
    @Entry public static float nightfall_obliterate_reduced_cooldown_per_level = 50;
    @Entry public static boolean nightfall_allow_non_undead_to_maybe_be_summoned = false;
    @Entry public static float nightfall_summoned_allies_cap = 50;
    @Entry(min=0, max=1) public static double nightfall_summon_chance = 0.3D;
    @Entry public static float nightfall_calculated_fall_base_radius = 3f;
    @Entry public static float nightfall_calculated_fall_height_increase_radius_modifier = 1.5f;
    @Entry public static float nightfall_calculated_fall_target_launch_modifier = 0.045f;
    @Entry public static float nightfall_calculated_fall_target_max_launch_power = 1.35f;
    @Entry public static float nightfall_calculated_fall_max_radius = 100f;
    @Entry public static float nightfall_calculated_fall_max_damage = 100f;
    @Entry public static float nightfall_calculated_fall_height_increase_damage_modifier = 0.2f;
    @Entry public static float nightfall_calculated_fall_heal_from_damage_modifier = 0f;
    @Entry public static float nights_edge_weapon_damage = 10;
    @Entry public static float nights_edge_weapon_attack_speed = 1.2f;
    @Entry public static float nights_edge_ability_cooldown = 120;
    @Entry public static float nights_edge_ability_min_cooldown = 40;
    @Entry public static boolean nights_edge_enchant_reduces_cooldown = false;
    @Entry public static String[] nights_edge_enchant_reduces_cooldown_ids = {"damage"};
    @Entry public static float nights_edge_ability_damage = 10f;
    @Entry public static float shadow_assassin_scythe_shadow_step_bonus_damage = 2f;
    @Entry public static float shadow_assassin_scythe_shadow_step_bonus_damage_per_shadow_step_amp = 0.5f;
    @Entry public static float shadow_assassin_scythe_attack_speed = 1f;
    @Entry public static float shadow_assassin_scythe_shadow_step_ticks = 60;
    @Entry public static float shadow_assassin_scythe_shadow_step_base_amp = 0;
    @Entry public static float shadow_assassin_scythe_shadow_step_bonus_amp_per_level = 0.8f;
    @Entry public static float shadow_assassin_scythe_shadow_step_cooldown = 160;
    @Entry public static float shadow_assassin_scythe_shadow_step_min_cooldown = 80;
    @Entry public static float shadow_assassin_scythe_shadow_step_reduced_cooldown_per_level = 20;
    @Entry public static float shadow_assassin_scythe_umbral_trespass_base_damage = 40f;
    @Entry public static float shadow_assassin_scythe_umbral_trespass_bonus_damage_per_level = 7.5f;
    @Entry public static float shadow_assassin_scythe_umbral_trespass_bonus_enchant_damage_modifier = 1f;
    @Entry public static float shadow_assassin_scythe_umbral_trespass_cooldown = 300;
    @Entry public static float shadow_assassin_scythe_umbral_trespass_min_cooldown = 100;
    @Entry public static float shadow_assassin_scythe_umbral_trespass_reduced_cooldown_per_level = 25;
    @Entry public static float shadow_assassin_scythe_ummbral_trespass_heal_modifier = 0f;
    @Entry public static float shadow_assassin_scythe_umbral_trespass_ticks_before_dismount = 120;
    @Entry(min=0,max=1) public static double shadow_assassin_scythe_umbral_trespass_bonus_percent_max_health_damage = 0f;
    @Entry public static float simons_blade_damage = 6;
    @Entry public static float simons_blade_attack_speed = 1.6f;
    @Entry public static float simons_blade_righteous_base_undead_bonus_damage = 3f;
    @Entry public static float simons_blade_righteous_undead_bonus_damage_per_level = 0.5f;
    @Entry public static float simons_bowblade_projectile_damage = 6;
    @Entry public static float simons_bowblade_bonus_velocity = 0f;
    @Entry public static float simons_bowblade_pull_time_ticks = 25;
    @Entry public static float simons_bowblade_projectile_righteous_base_undead_bonus_damage = 4f;
    @Entry public static float simons_bowblade_projectile_righteous_undead_bonus_damage_per_level = 0.5f;
    @Entry public static float simons_bowblade_projectile_posture_loss = 30;
    @Entry public static boolean simons_bowblade_projectile_can_apply_arrow_effects = true;
    @Entry public static float skofnung_damage = 8;
    @Entry public static float skofnung_attack_speed = 1.6f;
    @Entry public static float skofnung_bonus_damage = 2;
    @Entry public static float skofnung_disable_heal_duration = 100;
    @Entry public static float skofnung_stone_additional_empowered_strikes = 8;
    @Entry public static float skofnung_empowered_bleed_effect_duration = 200;
    @Entry public static float skofnung_empowered_bleed_effect_amp = 0;
    @Entry public static float skofnung_empowered_bleed_post_hit = 60;
    @Entry public static float soul_reaper_damage = 11;
    @Entry public static float soul_reaper_attack_speed = 1f;
    @Entry public static float soul_reaper_summoned_allies_cap = 50;
    @Entry public static float soul_reaper_summon_bonus_health_per_soul = 1f;
    @Entry public static float soul_reaper_summon_bonus_health_per_soul_addition_per_level = 0.2f;
    @Entry public static float soul_reaper_summon_max_bonus_health = 50f;
    @Entry public static float soul_reaper_summon_bonus_attack_damage_per_soul = 0.1f;
    @Entry public static float soul_reaper_summon_bonus_attack_damage_per_soul_addition_per_level = 0.05f;
    @Entry public static float soul_reaper_summon_max_bonus_attack_damage = 15f;
    @Entry public static float sting_damage = 6;
    @Entry public static float sting_attack_speed = 1.6f;
    @Entry public static float sting_bonus_arthropod_damage = 4f;
    @Entry public static float supernova_damage = 11f;
    @Entry public static float supernova_attack_speed = 1f;
    @Entry public static float supernova_posture_loss = 35;
    @Entry(min=0f,max=1f) public static float supernova_firehit_chance = 0.5f;
    @Entry public static float supernova_firehit_duration_seconds = 5f;
    @Entry public static float supernova_firethorns_damage = 4f;
    @Entry public static float supernova_firethorns_fire_seconds = 2f;
    @Entry(min=0f,max=1f) public static float supernova_firethorns_chance = 0.4f;
    @Entry public static float supernova_armor_breaker_bonus_stack_damage = 4f;
    @Entry public static float supernova_flame_pillar_base_damage = 10f;
    @Entry public static float supernova_flame_pillar_damage_per_level = 2f;
    @Entry public static float supernova_ability_flame_pillar_amount = 5f;
    @Entry public static float supernova_molten_metal_shield_damage = 100f;
    @Entry public static float supernova_molten_metal_fire_seconds = 4f;
    @Entry public static float supernova_molten_metal_max_age_ticks = 160f;
    @Entry public static float supernova_molten_metal_base_damage = 6f;
    @Entry public static float supernova_molten_metal_damage_per_level = 1f;
    @Entry public static float supernova_molten_metal_base_radius = 3f;
    @Entry public static float supernova_molten_metal_radius_per_level = 0.6f;
    @Entry public static float supernova_ability_cooldown = 180;
    @Entry public static float supernova_ability_min_cooldown = 40;
    @Entry public static float supernova_ability_reduced_cooldown_per_level = 15;
    @Entry public static float supernova_calculated_fall_base_radius = 1f;
    @Entry public static float supernova_calculated_fall_height_increase_radius_modifier = 1.25f;
    @Entry public static float supernova_calculated_fall_target_launch_modifier = 0.03f;
    @Entry public static float supernova_calculated_fall_target_max_launch_power = 1.25f;
    @Entry public static float supernova_calculated_fall_max_radius = 100f;
    @Entry public static float supernova_calculated_fall_max_damage = 100f;
    @Entry public static float supernova_calculated_fall_height_increase_damage_modifier = 0.1f;
    @Entry public static float supernova_calculated_fall_heal_from_damage_modifier = 0f;
    @Entry public static float supernova_calculated_fall_max_flame_pillar_ripples = 10f;
    @Entry public static float supernova_calculated_fall_height_increase_ripples_modifier = 0.16f;
    @Entry public static float sword_of_freyr_damage = 7;
    @Entry public static float sword_of_freyr_attack_speed = 1.6f;
    @Entry public static boolean sword_of_freyr_friendly_fire = true;
    @Entry public static double sword_of_freyr_health = 50D;
    @Entry public static double sword_of_freyr_armor = 10D;
    //@Entry public static float sword_of_freyr_animation_speed = 1.0f;
    @Entry public static float sword_of_the_nightlord_damage = 10;
    @Entry public static float sword_of_the_nightlord_attack_speed = 1.2f;
    @Entry public static float sword_of_the_nightlord_bonus_damage_per_potency_amp = 2f;
    @Entry public static float sword_of_the_nightlord_bonus_damage_if_target_is_afflicted = 2f;

    @Entry public static float sword_of_the_nightlord_base_bleed = 40;
    @Entry public static float sword_of_the_nightlord_bleed_duration = 60;
    @Entry public static float sword_of_the_nightlord_bleed_amp = 0;
    @Entry public static float sword_of_the_nightlord_poison_duration = 160;
    @Entry public static float sword_of_the_nightlord_poison_amp = 2;
    @Entry public static float sword_of_the_nightlord_chain_lightning_base_radius = 2.25f;
    @Entry public static float sword_of_the_nightlord_chain_lightning_radius_per_level = 0.8f;
    @Entry public static float sword_of_the_nightlord_chain_lightning_base_damage = 5f;
    @Entry public static float sword_of_the_nightlord_chain_lightning_damage_per_level = 2f;
    @Entry public static float sword_of_the_nightlord_wither_duration = 120;
    @Entry public static float sword_of_the_nightlord_wither_amp = 1;
    @Entry public static float sword_of_the_nightlord_frost_buildup_post_hit = 50;
    @Entry public static float sword_of_the_nightlord_permafrost_duration = 100;
    @Entry public static float sword_of_the_nightlord_permafrost_amp = 0;
    @Entry public static float sword_of_the_nightlord_fire_ticks = 200;
    @Entry public static float sword_of_the_nightlord_cripple_duration = 200;
    @Entry public static float sword_of_the_nightlord_slowness_amp = 1;
    @Entry public static float sword_of_the_nightlord_weakness_amp = 0;
    @Entry public static float sword_of_the_nightlord_mining_fatigue_amp = 0;
    @Entry public static float sword_of_the_nightlord_decay_duration = 100;
    @Entry public static float sword_of_the_nightlord_decay_amp = 0;
    @Entry public static float sword_of_the_nightlord_blight_duration = 200;
    @Entry public static float sword_of_the_nightlord_blight_amp = 3;

    @Entry public static float tonitrus_damage = 6;
    @Entry public static float tonitrus_attack_speed = 1.4f;
    @Entry public static float tonitrus_stormveil_effect_lightning_damage_heal = 2f;
    @Entry public static float tonitrus_stormveil_effect_duration = 400f;
    @Entry public static float tonitrus_stormveil_effect_base_amp = 0f;
    @Entry public static float tonitrus_stormveil_effect_amp_per_sharpness_enchant_ceiled = 0.8f;
    @Entry public static float tonitrus_stormveil_chain_lightning_damage_per_amp = 3f;
    @Entry public static float tonitrus_stormveil_chain_lightning_range_per_amp = 2f;
    @Entry(min=0f,max=1f) public static float tonitrus_stormveil_effect_electric_cherry_chance = 0.5f;
    @Entry public static float tonitrus_stormveil_effect_electric_cherry_base_damage = 2f;
    @Entry public static float tonitrus_stormveil_effect_electric_cherry_damage_per_amp_level = 3f;
    @Entry public static float tonitrus_stormveil_effect_electric_cherry_base_radius = 1f;
    @Entry public static float tonitrus_stormveil_effect_electric_cherry_radius_per_amp_level = 1f;
    @Entry public static float tonitrus_stormveil_effect_electric_cherry_heavy_slow_duration = 30f;
    @Entry public static float tonitrus_ability_cooldown = 80;
    @Entry public static float tonitrus_ability_min_cooldown = 10;
    @Entry public static float tonitrus_ability_reduced_cooldown_per_level = 10;
    @Entry public static float translucent_sword_damage = 6;
    @Entry public static float translucent_sword_attack_speed = 1.6f;
    @Entry public static float translucent_glaive_damage = 7;
    @Entry public static float translucent_glaive_attack_speed = 1.4f;
    @Entry public static float translucent_double_edged_greatsword_damage = 8;
    @Entry public static float translucent_double_edged_greatsword_attack_speed = 1.2f;
    @Entry public static float whirligig_sawblade_damage = 8;
    @Entry public static float whirligig_sawblade_attack_speed = 1.6f;
    @Entry public static float whirligig_sawblade_ability_damage = 5.0f;
    @Entry public static float whirligig_sawblade_bleed_added = 25;
    @Entry public static float whirligig_sawblade_bleed_effect_duration = 160;
    @Entry public static float whirligig_sawblade_bleed_effect_amp = 0;
    @Entry public static float whirligig_sawblade_cooldown = 100;
    @Entry public static float whirligig_sawblade_min_cooldown = 10;
    @Entry public static boolean whirligig_sawblade_enchant_reduces_cooldown = true;
    @Entry public static String[] whirligig_sawblade_enchant_reduces_cooldown_ids = {"damage"};
    @Entry public static float whirligig_sawblade_use_time = 100;
    @Entry public static float withered_wabbajack_damage = 8;
    @Entry public static float withered_wabbajack_attack_speed = 1.2f;

    @Entry public static boolean calculated_fall_hits_immune_entities = false;
    @Entry public static boolean ultra_heavy_haste_when_strength = true;
    @Entry public static boolean ultra_heavy_disable_offhand_when_held = false;
    @Entry public static boolean ultra_heavy_disables_shields = true;
    @Entry public static float ultra_heavy_posture_loss_modifier_when_stagger_enchant = 0.9f;
    @Entry public static boolean prioritize_off_hand_shield_over_weapon = false;

    @Entry public static boolean disable_posture_mechanic_for_all_mobs = false;
    @Entry public static float base_posture_unit = 120;
    @Entry public static float base_posture_buildup_resistance_unless_overridden = 0f;
    @Entry public static float posture_loss_reduction_amount = 1;
    @Entry public static float posture_loss_reduction_interval = 8;

    @Entry public static float posture_break_damage_per_amp = 6f;
    @Entry public static float posture_break_player_damage_per_amp = 2f;
    @Entry(min=0, max=1) public static float posture_break_percent_health_damage = 0.05f;

    @Entry public static boolean disable_bleed_mechanic_for_all_mobs = false;
    @Entry public static float max_bleed = 200;
    @Entry public static float base_bleed_buildup_resistance_unless_overridden = 0f;
    @Entry public static float base_bleed_damage_resistance_unless_overridden = 0f;
    @Entry public static float bleed_reduction_amount = 1;
    @Entry public static float bleed_reduction_interval = 10;
    @Entry public static float bleed_base_damage = 6f;
    @Entry(min=0, max=1) public static float bleed_percent_health_damage = 0.1f;
    @Entry public static float bleed_effect_increase_per_amp = 6;
    @Entry public static float bleed_effect_base_increase = 4;

    @Entry public static boolean disable_frost_buildup_mechanic_for_all_mobs = false;
    @Entry public static float max_frost_buildup = 200;
    @Entry public static float base_frost_buildup_resistance_unless_overridden = 0f;
    @Entry public static float base_frost_damage_resistance_unless_overridden = 0f;
    @Entry public static float frost_reduction_amount = 3;
    @Entry public static float frost_reduction_interval = 4;
    @Entry public static float frost_base_damage = 4f;
    @Entry(min=0, max=1) public static float frost_percent_health_damage = 0.15f;
    @Entry public static float frost_permafrost_spread_effect_amp = 2;
    @Entry public static float permafrost_effect_base_frost_buildup = 1;
    @Entry public static float permafrost_effect_buildup_per_amp = 1;

    @Entry(min=0) public static float blight_carrier_enchant_blight_duration = 160;
    @Entry(min=0) public static float blight_carrier_enchant_blight_per_level = 2;

    @Entry(min=0) public static float chain_lightning_enchant_damage_mod_per_level = 0.7f;
    @Entry(min=0) public static float chain_lightning_enchant_range_per_level = 2.25f;

    @Entry(min=0) public static boolean explosive_rounds_enchant_destroys_blocks = false;

    @Entry(min=0) public static float frostsilver_enchant_permafrost_per_level = 4;
    @Entry(min=0) public static float frostsilver_enchant_permafrost_duration = 100;

    @Entry(min=0) public static double misfire_curse_enchant_trigger_chance = 0.3;

    @Entry(min=0) public static float phantom_trace_enchant_phantom_projectile_damage_mod = 0.5f;


    @Entry(min=0) public static float ricochet_enchant_bounce_per_level = 1;

    @Entry(min=0) public static float stagger_enchant_posture_loss_applied_per_level = 5;
    @Entry(min=0) public static float stagger_enchant_posture_loss_on_player_modifier = 1f;

    @Entry(min=0) public static float tether_enchant_drag_mod = 1f;
    @Entry(min=0) public static float tether_enchant_min_activation_range_per_level = 3f;

    @Entry public static boolean enable_shield_parry = true;
    @Entry public static float shield_parry_cooldown = 40;
    @Entry(min=2) public static float shield_parry_max_animation_frames = 10;
    @Entry(min=2) public static float shield_parry_frames = 3;

    @Entry public static boolean chungus_tonic_can_change_entities = true;
    @Entry public static float chungus_tonic_ticks_until_chungified = 300;
    @Entry public static boolean can_chungus_barter = true;

    @Entry public static float blood_vial_heal = 5f;
    @Entry public static float blood_vial_regen_amp = 0;
    @Entry public static float blood_vial_regen_duration_ticks = 40;

    @Entry public static boolean can_projectiles_apply_posture_loss = true;
    @Entry public static float silver_bullet_undead_bonus_damage = 4f;
    @Entry(min=0) public static float silver_bullet_posture_loss_on_player_modifier = 0.75f;
    @Entry public static float blunderbuss_damage = 13f;
    @Entry public static float blunderbuss_velocity = 3f;
    @Entry public static float blunderbuss_divergence = 10f;
    @Entry public static float blunderbuss_projectile_amount = 3;
    @Entry public static float blunderbuss_posture_loss = 30;
    @Entry public static float blunderbuss_posture_loss_per_enchant_level = 3;
    @Entry public static float blunderbuss_cooldown = 80;
    @Entry public static float blunderbuss_bullets_needed = 2;
    @Entry public static float blunderbuss_bullets_needed_with_infinity = 2;
    @Entry public static float gatling_gun_damage = 3;
    @Entry public static float gatling_gun_velocity = 3f;
    @Entry public static float gatling_gun_divergence = 3f;
    @Entry public static float gatling_gun_posture_loss = 10;
    @Entry public static float gatling_gun_posture_loss_per_enchant_level = 3;
    @Entry public static float gatling_gun_max_time = 100;
    @Entry public static float gatling_gun_cooldown = 120;
    @Entry public static float gatling_gun_bullets_needed = 1;
    @Entry public static float gatling_gun_bullets_needed_with_infinity = 1;
    @Entry public static float hunter_cannon_damage = 30f;
    @Entry public static float hunter_cannon_velocity = 3f;
    @Entry public static float hunter_cannon_divergence = 1f;
    @Entry public static float hunter_cannon_posture_loss = 120;
    @Entry public static float hunter_cannon_posture_loss_per_enchant_level = 50;
    @Entry public static float hunter_cannon_cooldown = 300;
    @Entry public static float hunter_cannon_bullets_needed = 10;
    @Entry public static float hunter_cannon_bullets_needed_with_infinity = 10;
    @Entry public static float hunter_pistol_damage = 6f;
    @Entry public static float hunter_pistol_velocity = 3f;
    @Entry public static float hunter_pistol_divergence = 1f;
    @Entry public static float hunter_pistol_posture_loss = 50;
    @Entry public static float hunter_pistol_posture_loss_per_enchant_level = 10;
    @Entry public static float hunter_pistol_cooldown = 50;
    @Entry public static float hunter_pistol_bullets_needed = 1;
    @Entry public static float hunter_pistol_bullets_needed_with_infinity = 1;

    @Entry public static double dark_sorcerer_health = 10D;
    @Entry public static double dark_sorcerer_bonus_armor = 0D;

    @Entry public static double evil_forlorn_health = 30D;
    @Entry public static double evil_forlorn_bonus_armor = 0D;

    @Entry public static double forlorn_health = 30D;
    @Entry public static double forlorn_bonus_armor = 0D;

    @Entry public static double frost_giant_health = 50D;
    @Entry public static double frost_giant_armor = 8D;

    @Entry public static double moderatly_sized_chungus_heath = 14D;
    @Entry public static double moderatly_sized_chungus_armor = 0D;

    @Entry public static double remnant_health = 20D;
    @Entry public static double remnant_bonus_armor = 0D;

    @Entry public static double rime_spectre_health = 10D;
    @Entry public static double rime_spectre_armor = 0D;

    @Entry public static double soulmass_health = 75D;
    @Entry public static double soulmass_armor = 10D;

    @Entry public static double familiar_ghost_health = 10D;
    @Entry public static double familiar_ghost_armor = 0D;

    @Entry public static double warmth_health = 20D;
    @Entry public static double warmth_armor = 0D;

    @Entry public static double withered_demon_health = 80D;
    @Entry public static double withered_demon_armor = 2D;

    @Entry public static boolean decaying_king_disable_respawn = false;
    @Entry(min=1, max=1000000D) public static double decaying_king_health = 600D;
    @Entry(min=1, max=1000000D) public static double decaying_king_armor = 10D;
    @Entry(min=0) public static float decaying_king_attack_cooldown_ticks = 20;
    @Entry(min=0) public static float decaying_king_special_cooldown_ticks = 60;
    @Entry(min=0) public static float decaying_king_damage_modifier = 1f;
    @Entry(min=0) public static float decaying_king_xp = 500;
    @Entry public static boolean decaying_king_disables_shields = true;
    @Entry public static boolean decaying_king_is_fire_immune = true;
    @Entry public static boolean decaying_king_has_inverted_heal_and_harm = true;
    @Entry public static String[] decaying_king_status_effect_blacklist = {};

    @Entry public static boolean returning_knight_disable_respawn = false;
    @Entry(min=1, max=1000000D) public static double returning_knight_health = 500D;
    @Entry(min=1, max=1000000D) public static double returning_knight_armor = 15D;
    @Entry(min=0) public static float returning_knight_attack_cooldown_ticks = 40;
    @Entry(min=0) public static float returning_knight_special_cooldown_ticks = 80;
    @Entry(min=0) public static float returning_knight_summon_cooldown_ticks = 200;
    @Entry(min=0) public static float returning_knight_damage_modifier = 1f;
    @Entry(min=0) public static float returning_knight_xp = 500;
    @Entry public static String[] returning_knight_projectile_immunity_whitelist = {};
    @Entry public static boolean returning_knight_disables_shields = true;
    @Entry public static boolean returning_knight_is_fire_immune = true;
    @Entry public static boolean returning_knight_has_inverted_heal_and_harm = true;
    @Entry public static String[] returning_knight_status_effect_blacklist = {"minecraft:poison"};

    @Entry public static boolean old_champions_remains_disable_respawn = false;
    @Entry(min=1, max=1000000D) public static double old_champions_remains_health = 300D;
    @Entry(min=1, max=1000000D) public static double old_champions_remains_armor = 10D;
    @Entry(min=0) public static float old_champions_remains_attack_cooldown_ticks = 10;
    @Entry(min=0) public static float old_champions_remains_special_cooldown_ticks = 300;
    @Entry(min=0) public static float old_champions_remains_damage_modifier = 1f;
    @Entry public static float old_champions_remains_hits_before_growing_resistant = 3;
    @Entry public static float old_champions_remains_max_projectile_hits_before_immune = 3;
    @Entry public static float old_champions_remains_bleed_applied = 100;
    @Entry public static float old_champions_remains_xp = 200;
    @Entry public static boolean old_champions_remains_disables_shields = true;
    @Entry public static boolean old_champions_remains_disables_shields_all_attacks = false;
    @Entry public static boolean old_champions_remains_is_fire_immune = true;
    @Entry public static boolean old_champions_remains_has_inverted_heal_and_harm = true;
    @Entry public static String[] old_champions_remains_status_effect_blacklist = {"soulsweapons:bleed"};
    @Entry(min=1, max=1000000D) public static double frenzied_shade_health = 150D;
    @Entry(min=1, max=1000000D) public static double frenzied_shade_armor = 2D;
    @Entry public static float frenzied_shade_damage_modifier = 1f;
    @Entry public static float frenzied_shade_cooldown = 10;
    @Entry public static float frenzied_shade_xp = 400;
    @Entry public static boolean frenzied_shade_disables_shields = false;
    @Entry public static boolean frenzied_shade_is_fire_immune = true;
    @Entry public static boolean frenzied_shade_has_inverted_heal_and_harm = true;
    @Entry public static String[] frenzied_shade_status_effect_blacklist = {};

    @Entry public static boolean chaos_monarch_disable_respawn = false;
    @Entry(min=1, max=1000000D) public static double chaos_monarch_health = 450D;
    @Entry(min=1, max=1000000D) public static double chaos_monarch_armor = 4D;
    @Entry(min=0) public static float chaos_monarch_attack_cooldown_ticks = 20;
    @Entry(min=0) public static float chaos_monarch_damage_modifier = 1f;
    @Entry(min=0) public static float chaos_monarch_xp = 500;
    @Entry public static boolean chaos_monarch_wither_ground = true;
    @Entry public static boolean chaos_monarch_disables_shields = true;
    @Entry public static boolean chaos_monarch_is_fire_immune = true;
    @Entry public static boolean chaos_monarch_has_inverted_heal_and_harm = true;
    @Entry public static String[] chaos_monarch_status_effect_blacklist = {"soulsweapons:bleed", "minecraft:levitation", "minecraft:wither"};

    @Entry public static boolean fallen_icon_disable_respawn = false;
    @Entry(min=1, max=1000000D) public static double fallen_icon_health = 550D;
    @Entry(min=1, max=1000000D) public static double fallen_icon_armor = 20D;
    @Entry(min=0) public static float fallen_icon_attack_cooldown_ticks_phase_1 = 30;
    @Entry(min=0) public static float fallen_icon_attack_cooldown_ticks_phase_2 = 0;
    @Entry(min=0) public static float fallen_icon_special_cooldown_ticks = 50;
    @Entry(min=0) public static float fallen_icon_damage_modifier = 1f;
    @Entry(min=0) public static float fallen_icon_xp = 600;
    @Entry public static String[] fallen_icon_projectile_immunity_whitelist = {};
    @Entry public static boolean fallen_icon_disables_shields = true;
    @Entry public static boolean fallen_icon_is_fire_immune = true;
    @Entry public static boolean fallen_icon_has_inverted_heal_and_harm = false;
    @Entry public static String[] fallen_icon_status_effect_blacklist = {"minecraft:poison"};

    @Entry(min=1, max=1000000D) public static double day_stalker_health = 600D;
    @Entry(min=1, max=1000000D) public static double day_stalker_armor = 15D;
    @Entry(min=0) public static float day_stalker_damage_modifier = 1f;
    @Entry(min=0) public static float day_stalker_empowered_projectile_damage_taken_modifier_phase_1 = 0.8f;
    @Entry(min=0) public static float day_stalker_empowered_projectile_damage_taken_modifier_phase_2 = 0.6f;
    @Entry(min=0) public static float day_stalker_xp = 500;
    @Entry public static boolean day_stalker_disables_shields = true;
    @Entry public static boolean day_stalker_is_fire_immune = true;
    @Entry public static boolean day_stalker_has_inverted_heal_and_harm = false;
    @Entry(min=0, max=1) public static double day_stalker_projectile_cause_air_combustion_below_percent_health = 0.5;
    @Entry public static String[] day_stalker_status_effect_blacklist = {};
    @Entry(min=0) public static double day_stalker_cooldown_modifier_phase_1 = 1D;
    @Entry(min=0) public static double day_stalker_cooldown_modifier_phase_2 = 1D;
    @Entry(min=0) public static double day_stalker_special_cooldown_modifier_phase_1 = 1D;
    @Entry(min=0) public static double day_stalker_special_cooldown_modifier_phase_2 = 1D;
    @Entry(min=0) public static float duo_fight_time_before_switch = 400;
    @Entry(min=1, max=1000000D) public static double night_prowler_health = 500D;
    @Entry(min=1, max=1000000D) public static double night_prowler_armor = 10D;
    @Entry(min=0) public static float night_prowler_damage_modifier = 1f;
    @Entry(min=0) public static float night_prowler_eclipse_healing = 3f;
    @Entry(min=0) public static boolean night_prowler_eclipse_skulls_glow = false;
    @Entry(min=0, max=1) public static double night_prowler_projectile_heal_below_percent_health = 0.5;
    @Entry public static String[] night_prowler_projectile_immunity_whitelist = {};
    @Entry(min=0) public static float night_prowler_projectile_heal_amount = 5f;
    @Entry(min=0) public static double night_prowler_teleport_chance = 0.3D;
    @Entry(min=0) public static float night_prowler_xp = 500;
    @Entry public static boolean night_prowler_disables_shields = true;
    @Entry public static boolean night_prowler_is_fire_immune = true;
    @Entry public static boolean night_prowler_has_inverted_heal_and_harm = false;
    @Entry public static String[] night_prowler_status_effect_blacklist = {};
    @Entry(min=0) public static double night_prowler_cooldown_modifier_phase_1 = 1D;
    @Entry(min=0) public static double night_prowler_cooldown_modifier_phase_2 = 1D;
    @Entry(min=0) public static double night_prowler_special_cooldown_modifier_phase_1 = 1D;
    @Entry(min=0) public static double night_prowler_special_cooldown_modifier_phase_2 = 1D;
}