package net.soulsweaponry.util;

public enum TooltipAbilities {
    TRICK_WEAPON, GALEFORCE, LUNAR_HERALD, PARRY, FAST_PULL, THIRD_SHOT, SLOW_PULL, MOONLIGHT_ARROW,
    ARROW_STORM, TRANSPARENT, GUN_ITEM, PROJECTILE_POSTURE_LOSS,
    EMPEROR, EFFECT_REVERSAL, UNBREAKABLE, AFTERSHOCK, MIRROR, CORRUPT_GROUND, UNCEASING, INFECTIOUS, UNBURNABLE, EXALT,
    SET_BONUS
}
